apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  type: ClusterIP
  selector:
    app: config-service   # The label used to match the Pods to target and expose
  ports:
    - protocol: TCP
      port: 80            # The port exposed by the Service
      targetPort: 8071    # The port exposed by the Pods targeted by the Service